name: Discussions To Blog
description: 从 GitHub Discussions 中拉取指定 Category 帖子，并生成 Markdown 文件
author: zhanyeye

inputs:
  output_dir:
    description: "输出路径"
    required: true

runs:
  using: docker
  image: Dockerfile
